import type { PodcastEntry } from '@/types/books';

const podcast = (id: string, title: string, url: string, category: string): PodcastEntry => ({
  id, title, url, category,
  provider: new URL(url).hostname.replace(/^www\./, '').replace('podcasts.apple.com', 'Apple Podcasts').replace('open.spotify.com', 'Spotify').replace('music.amazon.com', 'Amazon Music').replace('youtube.com', 'YouTube').replace('drive.google.com', 'Google Drive'),
});

export const PODCASTS: PodcastEntry[] = [
  podcast('tjx-12-years-later', '44: 12 Years Later: How the TJX Hack Changed Security and Compliance', 'https://podcasts.apple.com/us/podcast/44-12-years-later-how-the-tjx-hack-changed-security/id1234621622?i=1000429814947', 'Cybersecurity'),
  podcast('albert-gonzalez-1', 'Malicious Life: The Life and Exploits of Albert Gonzalez — Part 1', 'https://www.cybereason.com/blog/malicious-life-podcast-the-life-and-exploits-of-albert-gonzales-part-1', 'Cybersecurity'),
  podcast('albert-gonzalez-2', 'Malicious Life: The Life and Exploits of Albert Gonzalez — Part 2', 'https://www.cybereason.com/blog/malicious-life-podcast-the-life-and-exploits-of-albert-gonzales-part-2', 'Cybersecurity'),
  podcast('albert-gonzalez-3', 'Malicious Life: The Life and Exploits of Albert Gonzalez — Part 3', 'https://www.cybereason.com/blog/malicious-life-podcast-the-life-and-exploits-of-albert-gonzales-part-3', 'Cybersecurity'),
  podcast('inside-tjx-heartland', 'Inside the TJX/Heartland Investigations', 'https://www.bankinfosecurity.com/inside-tjxheartland-investigations-a-2508', 'Cybersecurity'),
  podcast('nearest-neighbor-nexus', 'Nexus Podcast: Volexity’s Steven Adair on the Nearest Neighbor Attack', 'https://nexusconnect.io/podcasts/nexus-podcast-volexitys-steven-adair-on-the-nearest-neighbor-attack', 'Cybersecurity'),
  podcast('security-now-1002', 'Security Now: Disconnected Experiences', 'https://twit.tv/shows/security-now/episodes/1002', 'Cybersecurity'),
  podcast('nearest-neighbor-explained', 'Russian Hackers’ “Nearest Neighbor” Attack Explained', 'https://www.youtube.com/watch?v=DotlygY9Fkg', 'Cybersecurity'),
  podcast('steven-adair-wifi', 'Volexity’s Steven Adair on Russian Wi-Fi Hacks, Memory Analysis and Volt Typhoon', 'https://securityconversations.fireside.fm/steven-adair-nearest-neighbor-wifi-hack', 'Cybersecurity'),
  podcast('greynoise-russian-wifi', 'Russian Wi-Fi Hacks, Baltic Cable Sabotage, and Security Skills Poll Results', 'https://www.greynoise.io/storm-watch-episodes/russian-wi-fi-hacks-baltic-cable-sabotage-and-security-skills-poll-results', 'Cybersecurity'),
  podcast('risky-business-517', 'Risky Business #517 — Bloomberg’s Dumpster Fire Lights Up the PRC', 'https://risky.biz/RB517/', 'Cybersecurity'),
  podcast('wired-hotel-wifi', 'How Russian Spies Infiltrated Hotel Wi-Fi to Hack Victims Up Close', 'https://www.wired.com/story/russian-spies-indictment-hotel-wi-fi-hacking', 'Cybersecurity'),
  podcast('cyberwire-fancy-bear', 'CyberWire Daily: Fancy Bear’s in Hotel Wi-Fi', 'https://music.amazon.com/podcasts/76b35ca4-3e15-4c65-ba48-89588bead1fd/episodes/2001f2e8-44b6-4ff6-8feb-dc3e0e40d6be/cyberwire-daily-hbo-offered-mr-smith-a-bug-bounty-but-no-takers-fancy-bear%27s-in-hotel-wi-fi-dnc-leak-argument-resumes-locky-and-mamba-ransomware-are-back-isis-on-ebay-notpetya-arrest-wikileaks-dumps-more-from-vault7', 'Cybersecurity'),
  podcast('fancy-bear-cozy-bear', 'Malicious Life: Fancy Bear, Cozy Bear', 'https://www.cybereason.com/blog/malicious-life-podcast-fancy-bear-cozy-bear', 'Cybersecurity'),
  podcast('wireless-networks-dummies', 'Hacking Wireless Networks For Dummies', 'https://open.spotify.com/episode/3vWD6Q4VDHuBzEGxDjAyMN', 'Cybersecurity'),
  podcast('wardriving', 'Wardriving in Cybersecurity: Risks and Prevention Tips', 'https://www.youtube.com/watch?v=Ey_-iuSN4a4', 'Cybersecurity'),
  podcast('wireless-attacks', 'Wire-less Attacks That You Need to Be Aware Of', 'https://podcasts.apple.com/us/podcast/wire-less-attacks-that-you-need-to-be-aware-of/id1545960224?i=1000547744953', 'Cybersecurity'),
  podcast('strong-willed-kids', 'Why Are Some Kids So Strong-Willed And Stubborn!?', 'https://open.spotify.com/episode/4i5k1QZZLI2eVsMGxEZgs0', 'Parenting & wellbeing'),
  podcast('childhood-trauma-parenting', 'Why Does Childhood Trauma Impact Your Parenting? with Dr. Cotler', 'https://open.spotify.com/episode/7M76yYuffYnX4rakib7lpv', 'Parenting & wellbeing'),
  podcast('always-defensive', '“Why Are You Always So Defensive?”', 'https://open.spotify.com/episode/2bW16Aw7c6z8Vjnbax9BtX', 'Parenting & wellbeing'),
  podcast('ai-end-academia', 'How AI Will End Academia w/Jozef Gherman', 'https://podcasts.apple.com/gb/podcast/how-ai-will-end-academia-w-jozef-gherman/id1650150225?i=1000673584800', 'Education & ideas'),
  podcast('colin-and-samir', 'The Colin and Samir Show', 'https://open.spotify.com/show/5QaSbbv2eD4SFrlFR6IyY7', 'Culture & ideas'),
  podcast('hedx-30', 'HEDx Podcast — A Tribute to All Australian University Staff', 'https://soundcloud.com/campusreview/hedx-podcast-a-tribute-to-all-australian-university-staff-from-the-chair-of-ua-episode-30', 'Education & ideas'),
  podcast('latrobe-healthy-eating', 'La Trobe Thrive: Maintaining Healthy Eating Habits Within a Busy Lifestyle', 'https://open.spotify.com/episode/7EfFC8D7A73rRsw2fZn1Yu', 'Health & wellbeing'),
  podcast('latrobe-thrive', 'La Trobe University Thrive Health & Wellbeing Podcast', 'https://anchor.fm/la-trobe-sport', 'Health & wellbeing'),
  podcast('listnr-sleep', 'Sleep | LiSTNR', 'https://www.listnr.com/podcasts/sleep', 'Health & wellbeing'),
  podcast('unveiling-trauma', 'Unveiling Trauma: The Mind and Body Effects', 'https://open.spotify.com/show/1ozwIEgzEtHQezPoi83nVV', 'Mental health'),
  podcast('cbt-emdr-wellbeing', 'CBT - EMDR - Wellbeing - Mental Health', 'https://open.spotify.com/show/1Xz3zGVxfDLgidN8Vboko0', 'Mental health'),
  podcast('unveiling-trauma-episode', 'Unveiling Trauma: The Mind and Body Effects — Episode', 'https://open.spotify.com/episode/4ivGyyVgu79LvDFs7Xh5gj', 'Mental health'),
  podcast('cornerstone-community', 'Cornerstone Community Podcast', 'https://podcasts.apple.com/au/podcast/cornerstone-community-podcast/id293630407', 'Faith'),
  podcast('your-daily-prayer', 'Your Daily Prayer', 'https://open.spotify.com/show/7wNJMFDlJHmtGx6pLoTLsO', 'Faith'),
  podcast('beyond-busy-spotify', 'Beyond Busy', 'https://open.spotify.com/show/500RcyFLLYEFRwXwfWOsll', 'Culture & ideas'),
  podcast('beyond-busy-apple', 'Beyond Busy (Apple Podcasts)', 'https://podcasts.apple.com/gb/podcast/beyond-busy/id1093968526', 'Culture & ideas'),
  podcast('lex-fridman-apple', 'Lex Fridman Podcast (Apple Podcasts)', 'https://podcasts.apple.com/us/podcast/lex-fridman-podcast/id1434243584', 'Culture & ideas'),
  podcast('lex-fridman-spotify', 'Lex Fridman Podcast (Spotify)', 'https://open.spotify.com/show/2MAi0BvDc6GTFvKFPXnkCL', 'Culture & ideas'),
  podcast('crewcast-radio', 'Crewcast Radio', 'https://podcasts.apple.com/ca/podcast/crewcast-radio/id537311351', 'Fiction & entertainment'),
  podcast('spinward-fringe-24', 'The Spinward Fringe Podcast Broadcast 24 by Crewcast Radio', 'https://www.mixcloud.com/crewcastradio/the-spinward-fringe-podcast-broadcast-24', 'Fiction & entertainment'),
  podcast('crewcast-shows', 'Crewcast Radio’s Shows', 'https://www.mixcloud.com/crewcastradio', 'Fiction & entertainment'),
  podcast('crewcast-0', 'Crewcast Radio Broadcast 0', 'https://www.mixcloud.com/crewcastradio/crewcast-radio-broadcast-0', 'Fiction & entertainment'),
  podcast('peterson-musk-2024', 'Jordan Peterson x Elon Musk 2024 — THRIVE', 'https://open.spotify.com/episode/7yAYrfaI28hevsGHBQUYzJ', 'Culture & ideas'),
  podcast('2020-baby-pumping', '2020 Baby: Pumping Breast Milk for Your Baby', 'https://podcasts.apple.com/au/podcast/pumping-breast-milk-for-your-baby/id1506690037?i=1000515954902', 'Parenting & wellbeing'),
  podcast('2020-baby-birth-apple', '2020 Baby: Giving Birth — What Can I Do to Be Ready?', 'https://podcasts.apple.com/lu/podcast/giving-birth-what-can-i-do-to-be-ready/id1506690037?i=1000521585795', 'Parenting & wellbeing'),
  podcast('2020-baby-birth-amazon', '2020 Baby: Giving Birth — What Can I Do to Be Ready? (Amazon Music)', 'https://music.amazon.com/podcasts/01147c38-4849-47a0-b2fc-e01cbb470450/episodes/27ca9e05-3d7a-4928-8e30-5d005746710e/2020-baby-giving-birth-what-can-i-do-to-be-ready', 'Parenting & wellbeing'),
  podcast('covenant-eyes-spotify', 'The Covenant Eyes Podcast (Spotify)', 'https://open.spotify.com/show/3wmOwHbyoR6IyoZhXqfuWo', 'Faith & technology'),
  podcast('covenant-eyes-families', 'A New Way to Equip Families to Safely Navigate Technology, with Brock Murphy', 'https://open.spotify.com/episode/2rqmYwHkGNC1B1xcj1flkd', 'Faith & technology'),
  podcast('covenant-eyes-apple', 'The Covenant Eyes Podcast (Apple Podcasts)', 'https://podcasts.apple.com/au/podcast/the-covenant-eyes-podcast/id1608922111', 'Faith & technology'),
  podcast('covenant-eyes-amazon', 'The Covenant Eyes Podcast (Amazon Music)', 'https://music.amazon.com/podcasts/32d0ee9c-e653-4345-8979-222f7e2e2201/the-covenant-eyes-podcast', 'Faith & technology'),
  podcast('jre-1934', '#1934 — Lex Fridman — The Joe Rogan Experience', 'https://open.spotify.com/episode/4ho8NBQucRw6jkLP7F5Hlr', 'Culture & ideas'),
  podcast('taronga-talks', 'Taronga Talks', 'https://podcasts.apple.com/au/podcast/taronga-talks/id1456961572', 'Nature'),
  podcast('cornerstone-bendigo', 'Cornerstone Community Bendigo', 'https://podcasts.apple.com/au/podcast/cornerstone-community-bendigo/id1631658757', 'Faith'),
  podcast('depths-wikipedia-spotify', 'Depths of Wikipedia (Spotify)', 'https://open.spotify.com/show/2JC4liJrI1pqaf5YhzSB0d', 'Culture & ideas'),
  podcast('depths-wikipedia-apple', 'Depths of Wikipedia (Apple Podcasts)', 'https://podcasts.apple.com/au/podcast/depths-of-wikipedia/id1573347805', 'Culture & ideas'),
  podcast('feeling-good-cbt', 'Feeling Good Podcast — TEAM-CBT', 'https://open.spotify.com/show/3PkkHHHyaLZrMLtGuoIuxm', 'Mental health'),
  podcast('mycbt', 'MyCBT', 'https://open.spotify.com/show/3A2u4NLAH5I5bdguokRFPo', 'Mental health'),
  podcast('cbt-podcast', 'The CBT Podcast', 'https://open.spotify.com/show/0ACsnzSL7ob8CJgI7CGi4f', 'Mental health'),
  podcast('hypno-cbt', 'The Hypno-CBT Podcast with Arrive Therapy', 'https://open.spotify.com/show/1iwiyzy12YxNuF6cBaKYmR', 'Mental health'),
  podcast('talk-therapy-cbt', 'Talk Therapy CBT', 'https://open.spotify.com/show/5uPmXgKpYFV6A6kWhOh7v4', 'Mental health'),
  podcast('ministry-partner-june-2023', 'June 2023 — Interview with Dalene — Ministry Partner Podcast', 'https://open.spotify.com/episode/7GskybjRSG5jGHaZDko5Ma', 'Faith'),
  podcast('ministry-partner-may-2023', 'May 2023 — Ministry Partners — GRN Australia', 'https://open.spotify.com/episode/2LgWoAjfOD5gAWColQejFw', 'Faith'),
  podcast('spinward-fringe-1-2', 'Spinward Fringe Broadcasts 1 and 2: Resurrection and Awakening', 'https://soundcloud.com/user-954869728/online-spinward-fringe-broadcasts-1-and-2-resurrection-and-awakening-by-randolph-lalonde', 'Fiction & entertainment'),
  podcast('spinward-58', 'Triton Con 2021 Cardiff with the Author', 'https://drive.google.com/file/d/1-AmLsk4v7DsfP5SaUMBYA2T89zZfak4p/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('spinward-57', 'Blog — August 28, 2021', 'https://drive.google.com/file/d/16vZn8mSviccMRUlGH53LOSwe9YRLo4u8/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('spinward-56', 'Broadcast 10 Pre-Release Podcast', 'https://drive.google.com/file/d/1qeOChTvtgvsu6Pdjeyum_cgsG-ZPTBi2/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('spinward-55', 'Dark Arts Podcast 2', 'https://drive.google.com/file/d/1ZvMPNlPKOTFP1JrAI78VGGFajyLUn0bX/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('spinward-54', 'Dark Arts Podcast 1', 'https://drive.google.com/file/d/1L5CJ63PfgdRZKbOAdf1qomiODdHtxKn7/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('spinward-53', 'Spinward Fringe Broadcast 28', 'https://drive.google.com/file/d/1OYB0ks-WbKF_76Q9HOvTsHBCqVeECWq3/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('spinward-52', 'Spinward Fringe Broadcast 27', 'https://drive.google.com/file/d/1G1H28KCNlRrCRHsix6CkoQza0ci_iW7F/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('that-other-podcast-before-show', 'That Other Podcast — Before the Show', 'https://drive.google.com/file/d/1GXEDZBzTxnJD6iCMhU3H3m5wMVUMxGgs/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('spinward-50', 'Spinward Fringe Broadcast 26', 'https://drive.google.com/file/d/1ehZ7geqMeFEYBoCzqG8mpn6CnShBDKPg/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('that-geek-podcast-14', 'That Geek Podcast Episode 14', 'https://drive.google.com/file/d/1Gn046gsh6Oqc_XfTKf-0lMwXXIUcTyVp/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('that-geek-podcast-11-12', 'That Geek Podcast Episodes 11–12', 'https://drive.google.com/file/d/1x4UwZZD00Urds6WoMdfVvbp7TCqQbRwz/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('that-geek-podcast-news-13', 'That Geek Podcast: News and Gaming 13', 'https://drive.google.com/file/d/1a6-61w4uqRy5GxnECA_MqN6tDvnARtcP/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('spinward-46', 'Spinward Fringe Podcast 25', 'https://drive.google.com/file/d/1lQVzS8ZA2Ap7IaHVp6ymx9ohQVUfqJZi/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('that-geek-podcast-10', 'That Geek Podcast Episode 10', 'https://drive.google.com/file/d/1Fd-dDpQcHi1GC6bu_qGyJUb0JVEJA1XJ/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('that-geek-podcast-9', 'That Geek Podcast Episode 9', 'https://drive.google.com/file/d/1Z5wQehQ6bKgADCf6mBh2oR0hNpUkbQ6K/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('catalyst-17-2018', 'Catalyst Episode 17 (2018)', 'https://drive.google.com/file/d/1PPxopyjsKnpVCbQmNLz7nFnrh0LAL2zt/view?usp=drivesdk', 'Culture & ideas'),
  podcast('muster-2010-session-1', 'Muster 2010 — Session 1', 'https://drive.google.com/file/d/1zzx4mE4lRY-U-b7DhGXiCIvUycBMQgVU/view?usp=drivesdk', 'Events'),
  podcast('muster-2008-session-3', 'Muster 2008 — Session 3', 'https://drive.google.com/file/d/1hSxhVwsSJnu4ELAFISfRYgS96rj2Ho1Z/view?usp=drivesdk', 'Events'),
  podcast('muster-2008-session-1', 'Muster 2008 — Session 1', 'https://drive.google.com/file/d/1ctCjD-xeReZFiw5MIA5cGAtgp7xZCK64/view?usp=drivesdk', 'Events'),
  podcast('muster-2008-session-2', 'Muster 2008 — Session 2', 'https://drive.google.com/file/d/1Az0MwCeana2aK3NTSU9pIr1iq9CaF4zZ/view?usp=drivesdk', 'Events'),
  podcast('hamish-andy-absolute-radio', 'Hamish and Andy on Absolute Radio', 'https://drive.google.com/file/d/1hnC8AVW7611AxNAxVhvjLm4ApHdH2aNE/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-caravan-s2', "Hamish & Andy's Caravan of Courage — S2", 'https://drive.google.com/file/d/1hrZLJlWVZKsaBS9AUgWwYpyh282bDIiP/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-at-absolute-radio', 'Hamish & Andy at Absolute Radio', 'https://drive.google.com/file/d/1hooP2AR4fbc8UErtnqaDNjbyJ5zXz3KB/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-caravan-s', "Hamish & Andy's Caravan of Courage — S", 'https://drive.google.com/file/d/1hZOZonG-TV0iEqwqeYNC4g87I4mY3A7X/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-caravan-s1', "Hamish & Andy's Caravan of Courage — S1", 'https://drive.google.com/file/d/1i0AtWa5YuJd00uaKEwZMnncugskE5_dO/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-caravan-s4', "Hamish & Andy's Caravan of Courage — S4", 'https://drive.google.com/file/d/1i1uNJfKYh3RNkDdJSbMbjWWo7m3raM7x/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-guinea-pigs', 'Hamish & Andy — Guinea Pigs', 'https://drive.google.com/file/d/1dfLq37v0mDQZNGgs8impxd7R2AR4RbEf/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-doctors', 'Hamish & Andy — Doctors', 'https://drive.google.com/file/d/1gbry2s8cSHGUhnfdeE9QWcAhcnpm3BGD/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-pinching', 'Hamish & Andy — Pinching', 'https://drive.google.com/file/d/1djm6_A4qTPsKahTamQBitgn6zADaER8h/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-radio', 'Hamish & Andy — Radio', 'https://drive.google.com/file/d/1fgZVM_FI5SJJ3A10UAwLxq5pbmLzqyVg/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-secret-passageway', 'Hamish & Andy — Secret Passageway', 'https://drive.google.com/file/d/1h81R3_OD6Va2nl3vFZq49XKGQU72l6yY/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-talking-to-animal', 'Hamish & Andy — Talking to Animal', 'https://drive.google.com/file/d/1hEsDBRQ4RR2x_uXk6SVBcFZK-_6YYqGz/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-nun-the-wiser', 'Hamish & Andy — Nun the Wiser', 'https://drive.google.com/file/d/1gjnZZ1MDPZRJYuOag6E0mj2LfHJyjyRR/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-stadiums', 'Hamish & Andy — Stadiums', 'https://drive.google.com/file/d/1hNTu5lCijaj6-M85qJZswYpImAHQE0m9/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-irish', 'Hamish & Andy — The Irish', 'https://drive.google.com/file/d/1h3KKOWS3aRsspsbjiDbKBWQoTgv97g96/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-autographs', 'Hamish & Andy — Autographs', 'https://drive.google.com/file/d/1fZ-atX95skThJpIPCkRsiynEa-5G-eB0/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-father-son', 'Hamish & Andy — Father Son Activities', 'https://drive.google.com/file/d/1fp4LCfw8d9GxDmNpx3Gcr9jENV8N9iss/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-memories', 'Hamish & Andy — Memories', 'https://drive.google.com/file/d/1evKMirbx1MR53brFlkQjK1VAQDTqctTg/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-tattoos', 'Hamish & Andy — Tattoos', 'https://drive.google.com/file/d/1ezuoxvYWo6SdDFqQsNTzLXh9SJjrXHRZ/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-donald-trump', 'Hamish & Andy — Donald Trump', 'https://drive.google.com/file/d/1eWgik2SFGzrpIG-3npkbp9Xj-yjrbcvs/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-noises-you-love', 'Hamish & Andy — Noises You Love', 'https://drive.google.com/file/d/1fB5VGjGd6L23S6h1ICSAKfpbd1EDfyKE/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-burgers', 'Hamish & Andy — Burgers', 'https://drive.google.com/file/d/1ecXljbPgVgCdfPW_SNuwa-Jb7lIzTsNu/view?usp=drivesdk', 'Comedy'),
  podcast('hamish-andy-game-shows', 'Hamish & Andy — Game Shows', 'https://drive.google.com/file/d/1e1F5akHk6l4ILZ8InTf6dYKGPvsg582p/view?usp=drivesdk', 'Comedy'),
  podcast('ephesians-8-afflicted', 'Ephesians #8 — I Am Afflicted', 'https://drive.google.com/file/d/1dRAvWnJagi11VORs8g0s2X0DyCw3uT-F/view?usp=drivesdk', 'Faith'),
  podcast('jesus-sweats-blood', 'Jesus Sweats Blood', 'https://drive.google.com/file/d/1dDX6B7uAEqCItFS8eEeVts-MY9BtVSLr/view?usp=drivesdk', 'Faith'),
  podcast('porn-path', 'The Porn Path', 'https://drive.google.com/file/d/1cslTPC7LuQpfhi_zOZ2VYhzzt1PxHcTj/view?usp=drivesdk', 'Faith'),
  podcast('jesus-preached-gospel', 'Jesus Preached the Gospel', 'https://drive.google.com/file/d/1cjmj5e-rIu6VqnaH1HqWVj-OUbLE3Z1J/view?usp=drivesdk', 'Faith'),
  podcast('jesus-reconciles-us', 'Jesus Reconciles Us', 'https://drive.google.com/file/d/1cnmeWSaZtD5wa4YMetilrKw5vSk-HjeK/view?usp=drivesdk', 'Faith'),
  podcast('jesus-better-identity', 'Jesus Gives a Better Identity', 'https://drive.google.com/file/d/1citwA7aaDGqHvpxFwqjijWvIejP0A80I/view?usp=drivesdk', 'Faith'),
  podcast('ephesians-7-reconciled', 'Ephesians #7 — I Am Reconciled', 'https://drive.google.com/file/d/1c_siTFzTMGLCZVL9yNgnZXa8emtp77DR/view?usp=drivesdk', 'Faith'),
  podcast('significance-of-wisdom', 'Know the Significance of Wisdom', 'https://drive.google.com/file/d/1c1zUZ7z7yJjsr1apM_s_la4G5TPLL9xJ/view?usp=drivesdk', 'Faith'),
  podcast('power-your-words-have', 'Understand the Power Your Words Have', 'https://drive.google.com/file/d/1c6F4pRoFCRtNrFBqMtQ6ThzI36dmpXtG/view?usp=drivesdk', 'Faith'),
  podcast('ordinary-people-see', 'When Ordinary People See', 'https://drive.google.com/file/d/1cBzJkTm6nTZYrKWaewtYmHMx3fI8-sse/view?usp=drivesdk', 'Faith'),
  podcast('ordinary-people-serve', 'When Ordinary People Serve', 'https://drive.google.com/file/d/1cJfGXDTw2UyOyVGPGUk9SmXk0Ywu2SaN/view?usp=drivesdk', 'Faith'),
  podcast('ordinary-people-pray', 'When Ordinary People Pray', 'https://drive.google.com/file/d/1cMx4G-T3wYZkIp1RI_OPianlJi_47KcR/view?usp=drivesdk', 'Faith'),
  podcast('comfortable-own-grace-1', 'Being Comfortable in Your Own Grace — Part 1', 'https://drive.google.com/file/d/1cWm65PzTcy6ZULxPort9gBf3wnBiNdML/view?usp=drivesdk', 'Faith'),
  podcast('seven-classic-ways-1', 'Seven Classic Ways to Get Out Of — Part 1', 'https://drive.google.com/file/d/1cJaA6j5m1ouCbD3A_hwanyBEY-snRKq6/view?usp=drivesdk', 'Faith'),
  podcast('seven-classic-ways', 'Seven Classic Ways to Get Out Of', 'https://drive.google.com/file/d/1cN1e0YdKRyVbTkOuW0jtRTu8YXyeIi4z/view?usp=drivesdk', 'Faith'),
  podcast('comfortable-own-grace', 'Being Comfortable in Your Own Grace', 'https://drive.google.com/file/d/1c4BFMmLYmyPubsvJ0t8fBjW2_iIvdJMw/view?usp=drivesdk', 'Faith'),
  podcast('grace-who-you-are-1', 'Grace: Who You Are and Who You Are — Part 1', 'https://drive.google.com/file/d/1c_vB1oEumwXUlh_1vN6E6hp667TXG1Bl/view?usp=drivesdk', 'Faith'),
  podcast('grace-who-you-are', 'Grace: Who You Are and Who You Are', 'https://drive.google.com/file/d/1cQJ_GxCa9_ldyj3ijq3Df141Ca9LMXIi/view?usp=drivesdk', 'Faith'),
  podcast('living-own-grace-wisdom-1', 'Living in Your Own Grace: The Wisdom — Part 1', 'https://drive.google.com/file/d/1cRoxWGsU1kYmupWXQknCXKomrl1IRRcA/view?usp=drivesdk', 'Faith'),
  podcast('living-own-grace-wisdom', 'Living in Your Own Grace: The Wisdom', 'https://drive.google.com/file/d/1cPs8srAz7Ria91vZnkmsXQyqpiI0_mnK/view?usp=drivesdk', 'Faith'),
  podcast('godly-wisdom', 'Godly Wisdom', 'https://drive.google.com/file/d/1cXNuN_fCx76-7a_KwQwSPrPuhWbdJbdw/view?usp=drivesdk', 'Faith'),
];
