import type { PodcastEntry } from '@/types/books';

const podcast = (id: string, title: string, url: string, category: string): PodcastEntry => ({
  id, title, url, category,
  provider: new URL(url).hostname.replace(/^www\./, '').replace('podcasts.apple.com', 'Apple Podcasts').replace('open.spotify.com', 'Spotify').replace('music.amazon.com', 'Amazon Music').replace('youtube.com', 'YouTube').replace('drive.google.com', 'Google Drive'),
});

export const PODCASTS: PodcastEntry[] = [
  podcast('tjx-12-years-later', '44: 12 Years Later: How the TJX Hack Changed Security and Compliance', 'https://podcasts.apple.com/us/podcast/44-12-years-later-how-the-tjx-hack-changed-security/id1234621622?i=1000429814947', 'Cybersecurity'),
  podcast('albert-gonzalez-1', 'Malicious Life: The Life and Exploits of Albert Gonzalez — Part 1', 'https://www.cybereason.com/blog/malicious-life-podcast-the-life-and-exploits-of-albert-gonzales-part-1', 'Cybersecurity'),
  podcast('albert-gonzalez-2', 'Malicious Life: The Life and Exploits of Albert Gonzalez — Part 2', 'https://www.cybereason.com/blog/malicious-life-podcast-the-life-and-exploits-of-albert-gonzales-part-2', 'Cybersecurity'),
  podcast('albert-gonzalez-3', 'Malicious Life: The Life and Exploits of Albert Gonzalez — Part 3', 'https://www.cybereason.com/blog/malicious-life-podcast-the-life-and-exploits-of-albert-gonzales-part-3', 'Cybersecurity'),
  podcast('inside-tjx-heartland', 'Inside the TJX/Heartland Investigations', 'https://www.bankinfosecurity.com/inside-tjxheartland-investigations-a-2508', 'Cybersecurity'),
  podcast('nearest-neighbor-nexus', 'Nexus Podcast: Volexity’s Steven Adair on the Nearest Neighbor Attack', 'https://nexusconnect.io/podcasts/nexus-podcast-volexitys-steven-adair-on-the-nearest-neighbor-attack', 'Cybersecurity'),
  podcast('security-now-1002', 'Security Now: Disconnected Experiences', 'https://twit.tv/shows/security-now/episodes/1002', 'Cybersecurity'),
  podcast('nearest-neighbor-explained', 'Russian Hackers’ “Nearest Neighbor” Attack Explained', 'https://www.youtube.com/watch?v=DotlygY9Fkg', 'Cybersecurity'),
  podcast('steven-adair-wifi', 'Volexity’s Steven Adair on Russian Wi-Fi Hacks, Memory Analysis and Volt Typhoon', 'https://securityconversations.fireside.fm/steven-adair-nearest-neighbor-wifi-hack', 'Cybersecurity'),
  podcast('greynoise-russian-wifi', 'Russian Wi-Fi Hacks, Baltic Cable Sabotage, and Security Skills Poll Results', 'https://www.greynoise.io/storm-watch-episodes/russian-wi-fi-hacks-baltic-cable-sabotage-and-security-skills-poll-results', 'Cybersecurity'),
  podcast('risky-business-517', 'Risky Business #517 — Bloomberg’s Dumpster Fire Lights Up the PRC', 'https://risky.biz/RB517/', 'Cybersecurity'),
  podcast('wired-hotel-wifi', 'How Russian Spies Infiltrated Hotel Wi-Fi to Hack Victims Up Close', 'https://www.wired.com/story/russian-spies-indictment-hotel-wi-fi-hacking', 'Cybersecurity'),
  podcast('cyberwire-fancy-bear', 'CyberWire Daily: Fancy Bear’s in Hotel Wi-Fi', 'https://music.amazon.com/podcasts/76b35ca4-3e15-4c65-ba48-89588bead1fd/episodes/2001f2e8-44b6-4ff6-8feb-dc3e0e40d6be/cyberwire-daily-hbo-offered-mr-smith-a-bug-bounty-but-no-takers-fancy-bear%27s-in-hotel-wi-fi-dnc-leak-argument-resumes-locky-and-mamba-ransomware-are-back-isis-on-ebay-notpetya-arrest-wikileaks-dumps-more-from-vault7', 'Cybersecurity'),
  podcast('fancy-bear-cozy-bear', 'Malicious Life: Fancy Bear, Cozy Bear', 'https://www.cybereason.com/blog/malicious-life-podcast-fancy-bear-cozy-bear', 'Cybersecurity'),
  podcast('wireless-networks-dummies', 'Hacking Wireless Networks For Dummies', 'https://open.spotify.com/episode/3vWD6Q4VDHuBzEGxDjAyMN', 'Cybersecurity'),
  podcast('wardriving', 'Wardriving in Cybersecurity: Risks and Prevention Tips', 'https://www.youtube.com/watch?v=Ey_-iuSN4a4', 'Cybersecurity'),
  podcast('wireless-attacks', 'Wire-less Attacks That You Need to Be Aware Of', 'https://podcasts.apple.com/us/podcast/wire-less-attacks-that-you-need-to-be-aware-of/id1545960224?i=1000547744953', 'Cybersecurity'),
  podcast('strong-willed-kids', 'Why Are Some Kids So Strong-Willed And Stubborn!?', 'https://open.spotify.com/episode/4i5k1QZZLI2eVsMGxEZgs0', 'Parenting & wellbeing'),
  podcast('childhood-trauma-parenting', 'Why Does Childhood Trauma Impact Your Parenting? with Dr. Cotler', 'https://open.spotify.com/episode/7M76yYuffYnX4rakib7lpv', 'Parenting & wellbeing'),
  podcast('always-defensive', '“Why Are You Always So Defensive?”', 'https://open.spotify.com/episode/2bW16Aw7c6z8Vjnbax9BtX', 'Parenting & wellbeing'),
  podcast('ai-end-academia', 'How AI Will End Academia w/Jozef Gherman', 'https://podcasts.apple.com/gb/podcast/how-ai-will-end-academia-w-jozef-gherman/id1650150225?i=1000673584800', 'Education & ideas'),
  podcast('colin-and-samir', 'The Colin and Samir Show', 'https://open.spotify.com/show/5QaSbbv2eD4SFrlFR6IyY7', 'Culture & ideas'),
  podcast('hedx-30', 'HEDx Podcast — A Tribute to All Australian University Staff', 'https://soundcloud.com/campusreview/hedx-podcast-a-tribute-to-all-australian-university-staff-from-the-chair-of-ua-episode-30', 'Education & ideas'),
  podcast('latrobe-healthy-eating', 'La Trobe Thrive: Maintaining Healthy Eating Habits Within a Busy Lifestyle', 'https://open.spotify.com/episode/7EfFC8D7A73rRsw2fZn1Yu', 'Health & wellbeing'),
  podcast('latrobe-thrive', 'La Trobe University Thrive Health & Wellbeing Podcast', 'https://anchor.fm/la-trobe-sport', 'Health & wellbeing'),
  podcast('listnr-sleep', 'Sleep | LiSTNR', 'https://www.listnr.com/podcasts/sleep', 'Health & wellbeing'),
  podcast('unveiling-trauma', 'Unveiling Trauma: The Mind and Body Effects', 'https://open.spotify.com/show/1ozwIEgzEtHQezPoi83nVV', 'Mental health'),
  podcast('cbt-emdr-wellbeing', 'CBT - EMDR - Wellbeing - Mental Health', 'https://open.spotify.com/show/1Xz3zGVxfDLgidN8Vboko0', 'Mental health'),
  podcast('unveiling-trauma-episode', 'Unveiling Trauma: The Mind and Body Effects — Episode', 'https://open.spotify.com/episode/4ivGyyVgu79LvDFs7Xh5gj', 'Mental health'),
  podcast('cornerstone-community', 'Cornerstone Community Podcast', 'https://podcasts.apple.com/au/podcast/cornerstone-community-podcast/id293630407', 'Faith'),
  podcast('your-daily-prayer', 'Your Daily Prayer', 'https://open.spotify.com/show/7wNJMFDlJHmtGx6pLoTLsO', 'Faith'),
  podcast('beyond-busy-spotify', 'Beyond Busy', 'https://open.spotify.com/show/500RcyFLLYEFRwXwfWOsll', 'Culture & ideas'),
  podcast('beyond-busy-apple', 'Beyond Busy (Apple Podcasts)', 'https://podcasts.apple.com/gb/podcast/beyond-busy/id1093968526', 'Culture & ideas'),
  podcast('lex-fridman-apple', 'Lex Fridman Podcast (Apple Podcasts)', 'https://podcasts.apple.com/us/podcast/lex-fridman-podcast/id1434243584', 'Culture & ideas'),
  podcast('lex-fridman-spotify', 'Lex Fridman Podcast (Spotify)', 'https://open.spotify.com/show/2MAi0BvDc6GTFvKFPXnkCL', 'Culture & ideas'),
  podcast('crewcast-radio', 'Crewcast Radio', 'https://podcasts.apple.com/ca/podcast/crewcast-radio/id537311351', 'Fiction & entertainment'),
  podcast('spinward-fringe-24', 'The Spinward Fringe Podcast Broadcast 24 by Crewcast Radio', 'https://www.mixcloud.com/crewcastradio/the-spinward-fringe-podcast-broadcast-24', 'Fiction & entertainment'),
  podcast('crewcast-shows', 'Crewcast Radio’s Shows', 'https://www.mixcloud.com/crewcastradio', 'Fiction & entertainment'),
  podcast('crewcast-0', 'Crewcast Radio Broadcast 0', 'https://www.mixcloud.com/crewcastradio/crewcast-radio-broadcast-0', 'Fiction & entertainment'),
  podcast('peterson-musk-2024', 'Jordan Peterson x Elon Musk 2024 — THRIVE', 'https://open.spotify.com/episode/7yAYrfaI28hevsGHBQUYzJ', 'Culture & ideas'),
  podcast('2020-baby-pumping', '2020 Baby: Pumping Breast Milk for Your Baby', 'https://podcasts.apple.com/au/podcast/pumping-breast-milk-for-your-baby/id1506690037?i=1000515954902', 'Parenting & wellbeing'),
  podcast('2020-baby-birth-apple', '2020 Baby: Giving Birth — What Can I Do to Be Ready?', 'https://podcasts.apple.com/lu/podcast/giving-birth-what-can-i-do-to-be-ready/id1506690037?i=1000521585795', 'Parenting & wellbeing'),
  podcast('2020-baby-birth-amazon', '2020 Baby: Giving Birth — What Can I Do to Be Ready? (Amazon Music)', 'https://music.amazon.com/podcasts/01147c38-4849-47a0-b2fc-e01cbb470450/episodes/27ca9e05-3d7a-4928-8e30-5d005746710e/2020-baby-giving-birth-what-can-i-do-to-be-ready', 'Parenting & wellbeing'),
  podcast('covenant-eyes-spotify', 'The Covenant Eyes Podcast (Spotify)', 'https://open.spotify.com/show/3wmOwHbyoR6IyoZhXqfuWo', 'Faith & technology'),
  podcast('covenant-eyes-families', 'A New Way to Equip Families to Safely Navigate Technology, with Brock Murphy', 'https://open.spotify.com/episode/2rqmYwHkGNC1B1xcj1flkd', 'Faith & technology'),
  podcast('covenant-eyes-apple', 'The Covenant Eyes Podcast (Apple Podcasts)', 'https://podcasts.apple.com/au/podcast/the-covenant-eyes-podcast/id1608922111', 'Faith & technology'),
  podcast('covenant-eyes-amazon', 'The Covenant Eyes Podcast (Amazon Music)', 'https://music.amazon.com/podcasts/32d0ee9c-e653-4345-8979-222f7e2e2201/the-covenant-eyes-podcast', 'Faith & technology'),
  podcast('jre-1934', '#1934 — Lex Fridman — The Joe Rogan Experience', 'https://open.spotify.com/episode/4ho8NBQucRw6jkLP7F5Hlr', 'Culture & ideas'),
  podcast('taronga-talks', 'Taronga Talks', 'https://podcasts.apple.com/au/podcast/taronga-talks/id1456961572', 'Nature'),
  podcast('cornerstone-bendigo', 'Cornerstone Community Bendigo', 'https://podcasts.apple.com/au/podcast/cornerstone-community-bendigo/id1631658757', 'Faith'),
  podcast('depths-wikipedia-spotify', 'Depths of Wikipedia (Spotify)', 'https://open.spotify.com/show/2JC4liJrI1pqaf5YhzSB0d', 'Culture & ideas'),
  podcast('depths-wikipedia-apple', 'Depths of Wikipedia (Apple Podcasts)', 'https://podcasts.apple.com/au/podcast/depths-of-wikipedia/id1573347805', 'Culture & ideas'),
  podcast('feeling-good-cbt', 'Feeling Good Podcast — TEAM-CBT', 'https://open.spotify.com/show/3PkkHHHyaLZrMLtGuoIuxm', 'Mental health'),
  podcast('mycbt', 'MyCBT', 'https://open.spotify.com/show/3A2u4NLAH5I5bdguokRFPo', 'Mental health'),
  podcast('cbt-podcast', 'The CBT Podcast', 'https://open.spotify.com/show/0ACsnzSL7ob8CJgI7CGi4f', 'Mental health'),
  podcast('hypno-cbt', 'The Hypno-CBT Podcast with Arrive Therapy', 'https://open.spotify.com/show/1iwiyzy12YxNuF6cBaKYmR', 'Mental health'),
  podcast('talk-therapy-cbt', 'Talk Therapy CBT', 'https://open.spotify.com/show/5uPmXgKpYFV6A6kWhOh7v4', 'Mental health'),
  podcast('ministry-partner-june-2023', 'June 2023 — Interview with Dalene — Ministry Partner Podcast', 'https://open.spotify.com/episode/7GskybjRSG5jGHaZDko5Ma', 'Faith'),
  podcast('ministry-partner-may-2023', 'May 2023 — Ministry Partners — GRN Australia', 'https://open.spotify.com/episode/2LgWoAjfOD5gAWColQejFw', 'Faith'),
  podcast('spinward-fringe-1-2', 'Spinward Fringe Broadcasts 1 and 2: Resurrection and Awakening', 'https://soundcloud.com/user-954869728/online-spinward-fringe-broadcasts-1-and-2-resurrection-and-awakening-by-randolph-lalonde', 'Fiction & entertainment'),
  podcast('spinward-58', 'Triton Con 2021 Cardiff with the Author', 'https://drive.google.com/file/d/1-AmLsk4v7DsfP5SaUMBYA2T89zZfak4p/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('spinward-57', 'Blog — August 28, 2021', 'https://drive.google.com/file/d/16vZn8mSviccMRUlGH53LOSwe9YRLo4u8/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('spinward-56', 'Broadcast 10 Pre-Release Podcast', 'https://drive.google.com/file/d/1qeOChTvtgvsu6Pdjeyum_cgsG-ZPTBi2/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('spinward-55', 'Dark Arts Podcast 2', 'https://drive.google.com/file/d/1ZvMPNlPKOTFP1JrAI78VGGFajyLUn0bX/view?usp=drivesdk', 'Fiction & entertainment'),
  podcast('spinward-54', 'Dark Arts Podcast 1', 'https://drive.google.com/file/d/1L5CJ63PfgdRZKbOAdf1qomiODdHtxKn7/view?usp=drivesdk', 'Fiction & entertainment'),
];
